services:
  - type: web
    name: sheconnects-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DB_HOST
        value: 130.211.127.163
      - key: DB_USER
        value: root
      - key: DB_NAME
        value: sheconnects
      - key: DB_PORT
        value: 3306
      - key: FRONTEND_URL
        value: https://she-connects.vercel.app/
      - key: JWT_SECRET
        sync: false
      - key: DB_PASSWORD
        sync: false
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 1